---
title: "Examining the Effects of "
author: "Taeil Goh, Greg Tozzi & Max Ziff"
date: "11/17/2020"
output:
  html_document:
    toc: true
    toc_float: true
    css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

## Introduction and Context

### The Children’s Science Center

The Children’s Science Center (“the Center”) is a non-profit organization headquartered in Fairfax, Virginia.  Founded in TODO, the Center’s principal objective is to build the Northern Virginia region’s first interactive science center at a greenfield location on donated land in Reston, Virginia.  The capital campaign to raise fund to build this facility is the Center’s primary line of effort.  A recent partnership with the Commonwealth of Virginia’s 

Recognizing the long-term nature of the capital campaign and the need to build interest and advocacy, the Center launched a series of intermediate efforts beginning in TODO.  The Center’s first outreach effort was the Museum without Walls, a program that delivered science-based programs to schools around the region.  In TODO, the Center launched the Lab, a test facility located in a mall sited just outside of the Washington, DC Beltway.  The Lab hosted approximately TODO guests per year until it was temporarily shut down in response to the COVID-19 pandemic.

The Center funds operating expenses with Lab admissions, grants, and philanthropic giving.  The Center’s Development Department is responsible for developing and managing the latter two revenue streams.

### The Fundraising Surge

The Center conducts a fundraising surge toward the end of the calendar year, consistent with the charitable giving cycle in the United States [TODO: add reference].

The Center expected to engage the majority of its stakeholders by email.  The Center viewed email marketing as repeated iterations of a three step process.  The Development Director expected that several rounds of engagement would be necessary to achieve a conversion in the form of a charitable gift.  Within each individual round, the path to conversion proceeded from receipt to opening to click-through using an embedded link or button.

The Center introduced two major changes to its process ahead of the 2020 fundraising surge.  In previous year-end campaigns, the Center had used Constant Contact to send branded emails to stakeholders.  In the 2020 campaign, the Center chose to switch to Mail Chimp’s free tier.  The Center also engaged a consulting firm that applies machine learning to the nonprofit space to predict top prospects from among the Center’s contact list and to predict affinities to aspects of the Center’s mission.  The consulting firm’s model requires a physical address as an entering argument, and it was, therefore, only applied to that subset of the Center’s contact list for which physical addresses were entered.  Based on the consulting firm’s output, the Center chose to engage a subset of their stakeholder list with physical mail and to wall this cohort off from subsequent email engagement.

## Research Questions

We sought to answer two questions posed by the Center.  Both questions were related to emails sent by the Center soliciting donations.

1. Is there a difference in email opening or click-through caused by using the Executive Director’s name and title in the from line of the solicitation email versus using the Board Chair’s name and title?

2. Is there a difference in email opening or click-through behavior caused by the choice of using one of two potential subject lines?  The two subject lines considered were, “You can be a Catalyst for STEM Learning 💡," and , "Invest in the Power of STEM Learning 💡."

### Hypotheses

We claim expertise neither in non-profit email fundraising nor in the preferences of the Center's stakeholders.  The Center's development team believed that there would be a significant difference in the opening rates associated with the two email from lines considered, though the staff did not have a sense of which would result in significantly higher opening rates.  Underpinning the staff's expectation that we would find a significant difference was their belief that the Center's stakeholders had a meaningful sense of the Center's leadership and governance structure and would react differently when presented with emails from either the Executive Director or the Board Chair.

Both of the subject lines considered were written by the Center's development staff.  The staff believed that subject lines could result in significantly different opening rates but did not have a going-in belief of which subject line would cause a stronger response.

## Experimental Design

